import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";

const YOUTUBE_API_BASE = "https://www.googleapis.com/youtube/v3";

/**
 * YouTube Data API v3 subtitle extraction.
 * This is a fallback when yt-dlp is not available.
 */
export async function getYoutubeVideoInfo(
  videoId: string
): Promise<{
  title: string;
  author: string;
  duration?: number;
  thumbnail?: string;
  uploadDate?: string;
} | null> {
  const apiKey = process.env.YOUTUBE_API_KEY;
  if (!apiKey) return null;

  try {
    const params = new URLSearchParams({
      part: "snippet,contentDetails",
      id: videoId,
      key: apiKey,
    });

    const res = await fetch(`${YOUTUBE_API_BASE}/videos?${params}`);
    if (!res.ok) return null;

    const data = await res.json();
    if (!data.items || data.items.length === 0) return null;

    const item = data.items[0];
    const snippet = item.snippet;
    const contentDetails = item.contentDetails;

    // Parse duration (ISO 8601)
    const durationMatch = contentDetails?.duration?.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
    let duration: number | undefined;
    if (durationMatch) {
      duration =
        (parseInt(durationMatch[1] || "0") * 3600) +
        (parseInt(durationMatch[2] || "0") * 60) +
        parseInt(durationMatch[3] || "0");
    }

    return {
      title: snippet.title,
      author: snippet.channelTitle,
      duration,
      thumbnail: snippet.thumbnails?.maxres?.url || snippet.thumbnails?.high?.url,
      uploadDate: snippet.publishedAt?.split("T")[0],
    };
  } catch {
    return null;
  }
}

interface YoutubeCaption {
  id: string;
  snippet: {
    language: string;
    name: string;
    trackKind: string; // "standard" | "ASR" | "forced"
    isAutoSynced: boolean;
    isCC: boolean;
  };
}

export async function getYoutubeCaptions(
  videoId: string
): Promise<{ ccSubtitles: SubtitleTrack[]; autoTranslated: SubtitleTrack[] }> {
  const apiKey = process.env.YOUTUBE_API_KEY;
  if (!apiKey) return { ccSubtitles: [], autoTranslated: [] };

  try {
    const params = new URLSearchParams({
      part: "snippet",
      videoId,
      key: apiKey,
    });

    const res = await fetch(`${YOUTUBE_API_BASE}/captions?${params}`);
    if (!res.ok) return { ccSubtitles: [], autoTranslated: [] };

    const data = await res.json();
    const ccSubtitles: SubtitleTrack[] = [];
    const autoTranslated: SubtitleTrack[] = [];

    for (const item of (data.items || []) as YoutubeCaption[]) {
      const track: SubtitleTrack = {
        langCode: item.snippet.language,
        langName: item.snippet.name,
        isAutoGenerated: item.snippet.trackKind === "ASR",
        isTranslation: false,
      };

      if (item.snippet.trackKind === "standard") {
        ccSubtitles.push(track);
      } else if (item.snippet.trackKind === "ASR") {
        autoTranslated.push(track);
      }
    }

    return { ccSubtitles, autoTranslated };
  } catch {
    return { ccSubtitles: [], autoTranslated: [] };
  }
}
