import { exec } from "child_process";
import { promisify } from "util";
import path from "path";
import fs from "fs/promises";
import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";
import { detectFormat, convertSubtitle } from "./converter";

const execAsync = promisify(exec);
const YTDLP_PATH = "yt-dlp"; // Assumes yt-dlp is in PATH

interface YtDlpSubtitle {
  lang: string;
  name: string;
  url?: string;
  ext?: string;
}

interface YtDlpVideoInfo {
  id: string;
  title: string;
  description?: string;
  duration?: number;
  thumbnail?: string;
  upload_date?: string;
  uploader?: string;
  channel?: string;
  subtitles: Record<string, YtDlpSubtitle[]>;
  automatic_captions: Record<string, YtDlpSubtitle[]>;
}

export async function listSubtitles(url: string): Promise<{
  ccSubtitles: SubtitleTrack[];
  autoTranslated: SubtitleTrack[];
  videoInfo: {
    title: string;
    author: string;
    duration?: number;
    thumbnail?: string;
    uploadDate?: string;
    description?: string;
  } | null;
}> {
  try {
    const cmd = `"${YTDLP_PATH}" --dump-json --no-playlist --socket-timeout 30 "${url}"`;
    const { stdout } = await execAsync(cmd, {
      maxBuffer: 10 * 1024 * 1024,
      timeout: 30000,
    });

    const info: YtDlpVideoInfo = JSON.parse(stdout);

    const ccSubtitles: SubtitleTrack[] = [];
    const autoTranslated: SubtitleTrack[] = [];

    // Process CC subtitles
    if (info.subtitles) {
      for (const [langCode, subs] of Object.entries(info.subtitles)) {
        if (subs.length > 0) {
          ccSubtitles.push({
            langCode,
            langName: subs[0].name || langCode,
            url: subs[0].url,
            isAutoGenerated: false,
            isTranslation: false,
          });
        }
      }
    }

    // Process automatic captions
    if (info.automatic_captions) {
      for (const [langCode, subs] of Object.entries(info.automatic_captions)) {
        if (subs.length > 0) {
          // Skip if already in CC subtitles
          if (ccSubtitles.find((s) => s.langCode === langCode)) continue;

          autoTranslated.push({
            langCode,
            langName: `${subs[0].name || langCode} (自动)`,
            url: subs[0].url,
            isAutoGenerated: true,
            isTranslation: langCode !== "en" && langCode !== "zh-Hans" && langCode !== "zh-Hant",
          });
        }
      }
    }

    const videoInfo = {
      title: info.title || "Unknown",
      author: info.uploader || info.channel || "Unknown",
      duration: info.duration,
      thumbnail: info.thumbnail,
      uploadDate: info.upload_date,
      description: info.description,
    };

    return { ccSubtitles, autoTranslated, videoInfo };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("yt-dlp listSubtitles error:", errorMsg);
    return { ccSubtitles: [], autoTranslated: [], videoInfo: null };
  }
}

export async function downloadSubtitle(
  url: string,
  langCode: string,
  targetFormat: SubtitleFormat
): Promise<string | null> {
  const tmpDir = path.join(process.cwd(), "data", "tmp");
  await fs.mkdir(tmpDir, { recursive: true });

  try {
    // yt-dlp downloads as VTT by default
    const cmd = `"${YTDLP_PATH}" --write-subs --sub-lang "${langCode}" --sub-format vtt --skip-download -o "${tmpDir}/%(id)s.%(ext)s" --no-playlist --socket-timeout 30 "${url}"`;
    await execAsync(cmd, { maxBuffer: 10 * 1024 * 1024, timeout: 30000 });

    // Find the downloaded file
    const infoCmd = `"${YTDLP_PATH}" --dump-json --no-playlist --socket-timeout 30 "${url}"`;
    const { stdout: infoStdout } = await execAsync(infoCmd, {
      maxBuffer: 10 * 1024 * 1024,
      timeout: 30000,
    });
    const info = JSON.parse(infoStdout);
    const videoId = info.id;

    const files = await fs.readdir(tmpDir);
    const subtitleFile = files.find(
      (f) =>
        f.startsWith(videoId) &&
        (f.endsWith(`.${langCode}.vtt`) || f.includes(langCode))
    );

    if (!subtitleFile) {
      // Try without lang suffix
      const vttFiles = files.filter((f) => f.startsWith(videoId) && f.endsWith(".vtt"));
      if (vttFiles.length > 0) {
        const filePath = path.join(tmpDir, vttFiles[0]);
        const content = await fs.readFile(filePath, "utf-8");
        if (targetFormat !== "vtt") {
          return convertSubtitle(content, "vtt", targetFormat);
        }
        return content;
      }
      return null;
    }

    const filePath = path.join(tmpDir, subtitleFile);
    const content = await fs.readFile(filePath, "utf-8");

    // Convert if needed
    if (targetFormat !== "vtt") {
      return convertSubtitle(content, "vtt", targetFormat);
    }

    return content;
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("yt-dlp downloadSubtitle error:", errorMsg);
    return null;
  }
}
