"use client";

import { useState, useCallback } from "react";
import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";

export function useDownload() {
  const [downloadingLang, setDownloadingLang] = useState<string | null>(null);

  const download = useCallback(
    async (
      videoUrl: string,
      platform: string,
      videoId: string,
      track: SubtitleTrack,
      format: SubtitleFormat
    ) => {
      setDownloadingLang(track.langCode);

      try {
        const params = new URLSearchParams({
          videoUrl,
          platform,
          videoId,
          lang: track.langCode,
          type: track.isAutoGenerated ? "auto-generated" : "cc",
          format,
        });

        const res = await fetch(`/api/download?${params}`);
        if (!res.ok) {
          throw new Error("下载失败");
        }

        const blob = await res.blob();
        const downloadUrl = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = downloadUrl;

        const ext = format === "html" ? "html" : format;
        a.download = `subtitle_${track.langCode}_${track.isAutoGenerated ? "auto" : "cc"}.${ext}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(downloadUrl);
      } catch (err) {
        console.error("Download error:", err);
        alert("字幕下载失败，请尝试其他格式");
      } finally {
        setDownloadingLang(null);
      }
    },
    []
  );

  const downloadBilingual = useCallback(
    async (
      videoUrl: string,
      platform: string,
      videoId: string,
      first: SubtitleTrack,
      second: SubtitleTrack,
      format: SubtitleFormat
    ) => {
      setDownloadingLang(`${first.langCode}+${second.langCode}`);

      try {
        const res = await fetch("/api/bilingual", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            videoUrl,
            platform,
            videoId,
            firstLang: first.langName,
            secondLang: second.langName,
            firstLangCode: first.langCode,
            secondLangCode: second.langCode,
            format,
          }),
        });

        if (!res.ok) {
          const errData = await res.json();
          throw new Error(errData.error || "下载失败");
        }

        const blob = await res.blob();
        const downloadUrl = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = downloadUrl;
        a.download = `bilingual_${first.langCode}_${second.langCode}.${format}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(downloadUrl);
      } catch (err) {
        console.error("Bilingual download error:", err);
        alert("双语字幕下载失败，请确认两种语言的字幕均存在");
      } finally {
        setDownloadingLang(null);
      }
    },
    []
  );

  return { downloadingLang, download, downloadBilingual };
}
