export interface SubtitleTrack {
  langCode: string;
  langName: string;
  url?: string;
  isAutoGenerated: boolean;
  isTranslation: boolean;
  format?: SubtitleFormat;
  fileSize?: number;
}

export type SubtitleFormat = "srt" | "vtt" | "ass" | "txt" | "html";

export const SUBTITLE_FORMATS: SubtitleFormat[] = ["srt", "vtt", "ass", "txt", "html"];

export const SUBTITLE_FORMAT_LABELS: Record<SubtitleFormat, string> = {
  srt: "SRT",
  vtt: "VTT",
  ass: "ASS",
  txt: "TXT (纯文本)",
  html: "HTML",
};

export interface SubtitleSegment {
  index: number;
  start: number; // ms
  end: number; // ms
  text: string;
}

export interface SubtitleIR {
  segments: SubtitleSegment[];
  metadata?: {
    language?: string;
    title?: string;
    source?: string;
  };
}

export interface BilingualOptions {
  firstLang: string;
  secondLang: string;
  firstLangCode: string;
  secondLangCode: string;
  format: SubtitleFormat;
}
