"use client";

import { useState } from "react";
import { Download, ChevronDown } from "lucide-react";
import { cn, getLangFlag } from "@/lib/utils";
import { FormatSelector } from "./FormatSelector";
import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";

interface SubtitleItemProps {
  track: SubtitleTrack;
  onDownload: (track: SubtitleTrack, format: SubtitleFormat) => void;
  isLoading?: boolean;
}

export function SubtitleItem({ track, onDownload, isLoading }: SubtitleItemProps) {
  const [format, setFormat] = useState<SubtitleFormat>("srt");
  const flag = getLangFlag(track.langCode);

  return (
    <div className="flex items-center gap-3 rounded-lg border border-warm-border bg-white px-4 py-3 transition-all hover:shadow-subtle">
      <span className="text-xl flex-shrink-0">{flag}</span>
      <div className="flex-1 min-w-0">
        <span className="text-sm font-medium text-warm-text">{track.langName}</span>
        <span className="ml-2 text-xs text-warm-muted">({track.langCode})</span>
        {track.isAutoGenerated && (
          <span className="ml-2 inline-block rounded bg-amber-50 px-1.5 py-0.5 text-[10px] font-medium text-amber-700">
            AI
          </span>
        )}
      </div>
      <FormatSelector value={format} onChange={setFormat} />
      <button
        onClick={() => onDownload(track, format)}
        disabled={isLoading}
        className={cn(
          "flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium text-white transition-all active:scale-[0.97]",
          isLoading
            ? "bg-warm-muted cursor-not-allowed"
            : "bg-warm-orange hover:bg-warm-orange-hover"
        )}
      >
        <Download className="h-3.5 w-3.5" />
        <span className="hidden sm:inline">下载</span>
      </button>
    </div>
  );
}
