/**
 * Bilibili subtitle extraction logic.
 *
 * Bilibili uses a different system from YouTube:
 * - Subtitles are stored as JSON on their CDN
 * - Accessible via Bilibili API after getting video info
 * - Requires headers: Referer, User-Agent, sometimes Cookie
 */

import type { SubtitleTrack } from "@/types/subtitle";

const BILIBILI_VIDEO_INFO_API =
  "https://api.bilibili.com/x/web-interface/view";
const BILIBILI_SUBTITLE_API =
  "https://api.bilibili.com/x/player/v2";

export async function getBilibiliVideoInfo(
  bvid: string
): Promise<{
  title: string;
  author: string;
  duration: number;
  thumbnail: string;
  uploadDate: string;
  cid?: number;
} | null> {
  try {
    const params = new URLSearchParams({ bvid });
    const res = await fetch(`${BILIBILI_VIDEO_INFO_API}?${params}`, {
      headers: {
        Referer: "https://www.bilibili.com/",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      },
    });

    if (!res.ok) return null;
    const data = await res.json();
    if (data.code !== 0) return null;

    const videoData = data.data;
    return {
      title: videoData.title,
      author: videoData.owner?.name || "Unknown",
      duration: videoData.duration,
      thumbnail: videoData.pic,
      uploadDate: new Date(videoData.pubdate * 1000).toISOString().split("T")[0],
      cid: videoData.cid,
    };
  } catch {
    return null;
  }
}

export async function getBilibiliSubtitles(
  bvid: string,
  cid: number
): Promise<SubtitleTrack[]> {
  try {
    const params = new URLSearchParams({ bvid, cid: String(cid) });
    const res = await fetch(`${BILIBILI_SUBTITLE_API}?${params}`, {
      headers: {
        Referer: "https://www.bilibili.com/",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      },
    });

    if (!res.ok) return [];
    const data = await res.json();
    if (data.code !== 0) return [];

    const subtitles = data.data?.subtitle?.subtitles || [];

    return subtitles.map(
      (sub: { lan: string; lan_doc: string; subtitle_url: string }) => ({
        langCode: sub.lan,
        langName: sub.lan_doc || sub.lan,
        url: sub.subtitle_url,
        isAutoGenerated: sub.lan.includes("ai"),
        isTranslation: false,
      })
    );
  } catch {
    return [];
  }
}

export async function downloadBilibiliSubtitle(
  subtitleUrl: string
): Promise<string | null> {
  try {
    // Bilibili subtitle URLs may need https prefix
    const url = subtitleUrl.startsWith("http")
      ? subtitleUrl
      : `https:${subtitleUrl}`;

    const res = await fetch(url, {
      headers: {
        Referer: "https://www.bilibili.com/",
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
      },
    });

    if (!res.ok) return null;
    const data = await res.json();

    // Bilibili returns JSON format: { body: [{ from, to, content }] }
    const body = data.body || [];
    return bilibiliJsonToSRT(body);
  } catch {
    return null;
  }
}

function bilibiliJsonToSRT(
  segments: { from: number; to: number; content: string }[]
): string {
  return segments
    .map((seg, i) => {
      const start = formatSRTTime(seg.from);
      const end = formatSRTTime(seg.to);
      return `${i + 1}\n${start} --> ${end}\n${seg.content}\n`;
    })
    .join("\n");
}

function formatSRTTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")},${ms.toString().padStart(3, "0")}`;
}
