/**
 * Viki subtitle extraction logic.
 * Viki uses community-contributed subtitles in multiple languages.
 */

import type { SubtitleTrack } from "@/types/subtitle";

const VIKI_API_BASE = "https://www.viki.com/api/v4";

export async function getVikiVideoInfo(
  videoId: string
): Promise<{
  title: string;
  author: string;
  duration?: number;
  thumbnail?: string;
} | null> {
  try {
    const res = await fetch(`${VIKI_API_BASE}/videos/${videoId}.json`, {
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; SubExtract/1.0)",
      },
    });

    if (!res.ok) return null;
    const data = await res.json();

    return {
      title: data.title || "Unknown",
      author: data.author || "Viki",
      duration: data.duration,
      thumbnail: data.images?.poster || data.images?.thumbnail,
    };
  } catch {
    return null;
  }
}

export async function getVikiSubtitles(
  videoId: string
): Promise<SubtitleTrack[]> {
  try {
    const res = await fetch(
      `${VIKI_API_BASE}/videos/${videoId}/subtitles.json`,
      {
        headers: {
          "User-Agent": "Mozilla/5.0 (compatible; SubExtract/1.0)",
        },
      }
    );

    if (!res.ok) return [];
    const data = await res.json();

    return (data.subtitles || data.data || []).map(
      (sub: { language?: string; lang_code?: string; language_name?: string }) => ({
        langCode: sub.language || sub.lang_code || "unknown",
        langName: sub.language_name || sub.language || sub.lang_code || "Unknown",
        isAutoGenerated: false,
        isTranslation: false,
      })
    );
  } catch {
    return [];
  }
}
