/**
 * YouTube-specific subtitle extraction logic.
 *
 * YouTube provides three types of captions:
 * 1. CC (Closed Captions) - uploaded by creator
 * 2. ASR (Automatic Speech Recognition) - auto-generated by YouTube
 * 3. Auto-translated - ASR captions translated to another language
 *
 * Extraction methods:
 * - Primary: yt-dlp (handles all YouTube caption types)
 * - Secondary: YouTube Data API v3 (API key required)
 * - Fallback: timedtext API (direct internal API call)
 */

import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";

const TIMEDTEXT_API = "https://www.youtube.com/api/timedtext";

interface TimedTextParams {
  v: string; // videoId
  lang: string;
  fmt?: string;
  tlang?: string;
  kind?: string;
}

export function buildTimedTextUrl(params: TimedTextParams): string {
  const searchParams = new URLSearchParams();
  searchParams.set("v", params.v);
  searchParams.set("lang", params.lang);
  if (params.fmt) searchParams.set("fmt", params.fmt);
  if (params.tlang) searchParams.set("tlang", params.tlang);
  if (params.kind) searchParams.set("kind", params.kind);
  return `${TIMEDTEXT_API}?${searchParams.toString()}`;
}

export async function fetchTimedText(
  videoId: string,
  langCode: string,
  options?: { tlang?: string; format?: SubtitleFormat }
): Promise<string | null> {
  try {
    const fmt = options?.format === "srt" ? "srv3" : "vtt";
    const params: TimedTextParams = {
      v: videoId,
      lang: langCode,
      fmt,
    };
    if (options?.tlang) {
      params.tlang = options.tlang;
    }

    const url = buildTimedTextUrl(params);
    const res = await fetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; SubExtract/1.0)",
      },
    });

    if (!res.ok) return null;
    return await res.text();
  } catch {
    return null;
  }
}

export async function getAvailableLanguages(
  videoId: string
): Promise<SubtitleTrack[]> {
  try {
    const url = buildTimedTextUrl({ v: videoId, lang: "en", fmt: "vtt" });
    // YouTube's timedtext API returns XML with available languages
    // We use a simpler approach: try common languages and see what's available
    const commonLangs = [
      { code: "en", name: "English" },
      { code: "zh-Hans", name: "中文(简体)" },
      { code: "zh-Hant", name: "中文(繁體)" },
      { code: "ja", name: "日本語" },
      { code: "ko", name: "한국어" },
      { code: "es", name: "Español" },
      { code: "fr", name: "Français" },
      { code: "de", name: "Deutsch" },
      { code: "pt", name: "Português" },
      { code: "ru", name: "Русский" },
      { code: "ar", name: "العربية" },
      { code: "hi", name: "हिन्दी" },
      { code: "th", name: "ไทย" },
      { code: "vi", name: "Tiếng Việt" },
      { code: "id", name: "Bahasa Indonesia" },
      { code: "it", name: "Italiano" },
      { code: "nl", name: "Nederlands" },
      { code: "tr", name: "Türkçe" },
      { code: "pl", name: "Polski" },
    ];

    // We return the full list; yt-dlp handles the actual availability check
    return commonLangs.map((l) => ({
      langCode: l.code,
      langName: l.name,
      isAutoGenerated: true,
      isTranslation: l.code !== "en",
    }));
  } catch {
    return [];
  }
}
